# DNSMasq Config
interface=eth0
bind-dynamic

# Do not read /etc/resolv.conf
no-resolv

# Do not read /etc/hosts
no-hosts

# Avoid Reusing Old Or Broken DHCP Clients.
dhcp-no-override

#Set The Number Of Cached Domain Names
cache-size=10000

# The Address 192.168.0.100 Is The Static IPv4 Of This Server
listen-address=127.0.0.1
listen-address=192.168.0.100

# OpenDNS IPv4 Source DNS Servers
server=208.67.222.222
server=208.67.220.220

# OpenDNS IPv6 Source DNS Servers
server=2620:119:35::35
server=2620:119:53::53

# DHCP IPv4 Options
dhcp-range=192.168.0.21,192.168.0.250,255.255.255.0,24h
#domain=cable.virginm.net
domain=dangerhq.local
dhcp-option=option:ntp-server,109.74.197.50
dhcp-option=option:domain-name,dangerhq.local
dhcp-option=option:router,192.168.0.1
dhcp-option=option:dns-server,208.67.222.222,208.67.220.220

# DHCP IPv6 Options
dhcp-option=option6:dns-server,[2620:119:35::35,2620:119:53::53]

# DHCP IPv4 Static Addresses
dhcp-host=5c:a6:e6:b7:66:52,192.168.0.2,Lounge_TL-SG105PE_eth
dhcp-host=00:11:32:25:5c:6d,192.168.0.3,DangerHQ-DS414_eth
dhcp-host=ec:71:db:3e:ea:b3,192.168.0.4,Swann-DVR_eth
dhcp-host=f4:cf:a2:f3:1f:c3,192.168.0.5,espressif_wlan
dhcp-host=2c:58:b9:5c:9a:48,192.168.0.6,HP-MFP-4302_eth
dhcp-host=a8:6e:84:1b:b7:6e,192.168.0.7,Office_TL-SG108PE_eth
dhcp-host=d8:3a:dd:a4:0c:ac,192.168.0.10,Rpi-PhotoFrame-x64_wlan
dhcp-host=2c:cf:67:5c:99:af,192.168.0.11,RetroPie-Lounge-x64_wlan
dhcp-host=dc:a6:32:40:c5:ce,192.168.0.12,RetroPie-BedRoom-x64_wlan
dhcp-host=40:d2:8a:32:2d:1c,192.168.0.13,Nintendo-WiiU_wlan
dhcp-host=b0:41:1d:3d:a3:f2,192.168.0.14,SWANN-PTCAM_wlan


# DHCP IPv6 Static Addresses
dhcp-host=set:static,5c:a6:e6:b7:66:52,[::2],Lounge_TL-SG105PE_eth
dhcp-host=set:static,00:11:32:25:5c:6d,[::3],DangerHQ-DS414_eth
dhcp-host=set:static,ec:71:db:3e:ea:b3,[::4],Swann-DVR_eth
dhcp-host=set:static,f4:cf:a2:f3:1f:c3,[::5],espressif_wlan
dhcp-host=set:static,2c:58:b9:5c:9a:48,[::6],HP-MFP-4302_eth
dhcp-host=set:static,a8:6e:84:1b:b7:6e,[::7],Office_TL-SG108PE_eth
dhcp-host=set:static,d8:3a:dd:a4:0c:ac,[::10],Rpi-PhotoFrame-x64_wlan
dhcp-host=set:static,2c:cf:67:5c:99:af,[::11],RetroPie-Lounge-x64_wlan
dhcp-host=set:static,dc:a6:32:40:c5:ce,[::12],RetroPie-BedRoom-x64_wlan
dhcp-host=set:static,40:d2:8a:32:2d:1c,[::13],Nintendo-WiiU_wlan
dhcp-host=set:static,b0:41:1d:3d:a3:f2,[::14],SWANN-PTCAM_wlan
